version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://postgres:root@db:5432/safedrive
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_API_KEY=AlzaSyaJ4IYEVTHw7le73725wbbLS23xKmr
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    command: flask run --host=0.0.0.0

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: safedrive
    ports:
      - "5432:5432"
